// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBR6FhntryQv0MPFgxaEpoa_Gi_lhpQf58',
    appId: '1:284502733106:web:2417a7eb53098270ad272b',
    messagingSenderId: '284502733106',
    projectId: 'danzify-2a2ec',
    authDomain: 'danzify-2a2ec.firebaseapp.com',
    storageBucket: 'danzify-2a2ec.appspot.com',
    measurementId: 'G-PBX1NLKH5B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-uhkQZ6ZyR8ElYqG0QJ_8G1yNi4ewjJ4',
    appId: '1:284502733106:android:bfab9abd3860bc5bad272b',
    messagingSenderId: '284502733106',
    projectId: 'danzify-2a2ec',
    storageBucket: 'danzify-2a2ec.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHZ-2sZrOatEhht4Cn_ua6MWe8oKYdlIQ',
    appId: '1:284502733106:ios:6c876f08700c7e85ad272b',
    messagingSenderId: '284502733106',
    projectId: 'danzify-2a2ec',
    storageBucket: 'danzify-2a2ec.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHZ-2sZrOatEhht4Cn_ua6MWe8oKYdlIQ',
    appId: '1:284502733106:ios:6c876f08700c7e85ad272b',
    messagingSenderId: '284502733106',
    projectId: 'danzify-2a2ec',
    storageBucket: 'danzify-2a2ec.appspot.com',
    iosBundleId: 'com.example.quiz',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBR6FhntryQv0MPFgxaEpoa_Gi_lhpQf58',
    appId: '1:284502733106:web:0189272559edb0dcad272b',
    messagingSenderId: '284502733106',
    projectId: 'danzify-2a2ec',
    authDomain: 'danzify-2a2ec.firebaseapp.com',
    storageBucket: 'danzify-2a2ec.appspot.com',
    measurementId: 'G-1Y3M6N8YF3',
  );

}